id: PECD8DF6C
initial_creation_type: ocr
source_metadata:
  volumes:
    3c33163d243a4c1eb1b61abeba1401bd:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: བྱང་ཆུབ་སེམས་དཔའི་ཚུལ་ཁྲིམས་ཀྱི་ལེའུའི་བཤད་པ།
      total_pages: 1529
      volume_number: 75
